services:
  postgres:
    image: postgres:16
    container_name: taskflow_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: taskflow
    ports:
      - "5432:5432"
    volumes:
      - taskflow_db_data:/var/lib/postgresql/data

volumes:
  taskflow_db_data:
